name: test-and-publish
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.4
      - run: npm ci
      - run: npm run build
      - run: npm run test
        env:
          CI: true
  publish:
    if: github.ref == 'refs/heads/master'
    name: publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}